### ISSUE TITLE
No checks for national ID

### ISSUE THREAD

**Issue by KhunakornP** [Pong50887/RentHub-Connect#141]
## **Bug**
You can enter any combination of numbers as a national ID

## **How To Reproduce**
1. Create a profile
2. Add a nonsense group of numbers as an ID

## **Additional notes**
You didn't even ask for a photo of my national ID, Even if I gave you a valid nat ID how are you going to verify it?

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**

![id](https://github.com/user-attachments/assets/4d543585-25c2-466d-b93c-228c51d2b213)

**Comment by KhunakornP** [comment]
Also, What if I Legally change my name? Am I forever stuck as "a"?

 Additionally, I noticed that you cannot have the same National ID as another user, Which makes sense but if you allow some rando to add any ID they want what if the actual person who owns the ID tries to create an account? They would not be able to!

**Comment by Karczel** [comment]
Thanks! for your inquiries
1. We will add form to submit a picture of your ID for proof of identity, whereas the admin will manually check for your validity before allowing you're allowed to rent, and since this is an application for local apartment management, they can just check in with the person irl
2. Realistically, admin will check your info along with your citizenship id card, so you'd have to contact the admin for any inconsistencies with your legal information and have them correct your information, therefore users still shouldn't be able to edit this information, or hard to change as a renter.
3. This will be taken care of once 1. is implemented

Note: 
Please don't storm our website with uploading multiple images, as AWS free plan limited requests to 2000 a year, meaning exceeding this limit will result in me being charged for it. 😣🙏💦

**Comment by Karczel** [comment]
I admire your attention to detail, you would make for a great white hat hacker!
I have unimplemented projects planned for the future, may I ask you to look into it, if it's not inconveniencing you?

**Comment by KhunakornP** [comment]
> Note: 
> Please don't storm our website with uploading multiple images, as AWS free plan limited requests to 2000 a year, meaning exceeding this limit will result in me being charged for it. 😣🙏💦

That was not me btw, you've got the wrong man. Unless you count me booking like 3 rooms a lot of images. 

Or did I book more? I'm sorry if I did.

**Comment by Karczel** [comment]
> booking

Oh so someone created a bunch of jail room objects for rent in droves after they've gained access through the admin for 'DEMO user' in the README.md, which had been changed and removed, along with those newly created rooms.
So I don't think that's the problem, but since many people test the website, it can aggregate up fast. Thanks for letting me know!

**Comment by Thanawas-Sirilertsathit** [comment]
![image](https://github.com/user-attachments/assets/a8bb730e-2c2c-4548-85ed-103d784abcc5)
Now you know who did it.
![image](https://github.com/user-attachments/assets/256afa37-9818-49b3-a9cb-373e3ef172c5)

**Comment by Karczel** [comment]
???
sorry I didn't get what you meant

**Comment by Thanawas-Sirilertsathit** [comment]
I mean I did it. Sorry for attacking your server. Also if you already fix please close the issue #149 .

**Comment by Karczel** [comment]
Thank you for informing me!

**Comment by Thanawas-Sirilertsathit** [comment]
Also the issue about image file field for payment slip. Does it solve? @Karczel

**Comment by Thanawas-Sirilertsathit** [comment]
#144 I can upload any file type.
Yeah I really can.

**Comment by Thanawas-Sirilertsathit** [comment]
You should link the issue to PR when merge into main. Not just close it right away when it is not fixed yet.

**Comment by Karczel** [comment]
oh I'm only responsible for this issue and Phone Number Field Allows Non-Numeric Input
I think it would be fixed once we merge bugFix and redeploy the project again so please standby

**Comment by Thanawas-Sirilertsathit** [comment]
Suggestion : Other than limit image file type, you also should limit image file size like 100MB to make your storage harder to be attacked.

**Comment by Karczel** [comment]
I've sent your concern forward, in the bugFix branch we have limit to only image files upload but as for size I'm awaiting response from the team, thank you so much!

**Comment by Karczel** [comment]
I think there should be a method for admin to approve renter accounts, hold on
I figured admin should check renter's credentials when approving rentals anyways, so no more changes needed

so admin can check from the admin page in rental management page whether the renter who submitted the rental request is verified or not, and may reject them based on that information.
we choose to handle checking with this since otherwise we'd have to go in and change all code related to renting, and we simply are running out of time, thus we propagate the approval decision to admin
