### ISSUE TITLE
Incorrect Notification When Needing to Contact/Report a Problem

### ISSUE THREAD

**Issue by colarrbear** [Pong50887/RentHub-Connect#147]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/3bab29ab-2cf9-4680-9f31-499f6fbdefe1">

I believe it may not be necessary to have a rental associated with my account in order to reach out. As a test customer, if I encounter a bug that I would like to report to the developers, can I do so without needing an active rental?

[Using in MacOS 14.6.1 with Arc Browser]

**Comment by PHIMNADA024** [comment]
Apologies for any confusion regarding this page. It is intended for reporting problems related to a rental, such as a broken tap. You need to have an active rental to use this feature. Since this doesn't appear to be a defect, I will close this issue. If you have any further concerns or questions, please let us know. Thank you!
