### ISSUE TITLE
Perform checksum on Thai ID

### ISSUE THREAD

**Issue by jbrucker** [Pong50887/RentHub-Connect#152]
Your app requires user to input Thai National ID,
but does not seem to check for valid ID.
There is a checksum formula you can use to verify
the ID has valid format.  It would help detect
typing errors.

**Comment by Karczel** [comment]
I've added validation to attribute thai_citizenship_id in Renter model, pre-existing accounts may still have incorrect thai_citizenship_id data but you are not allowed to create new accounts with wrong checksum thai citizenship id or save edited renter changes by admin until the thai citizenship id passed the checksum validation


You may have to wait for re-deployment on from render service to test this

**Comment by Karczel** [comment]
on the other note, can I tag you to ask for your opinion(s) on my other project(s), like QAPizza? (my project proposal for the project that I didn't do due to lacking team members) I'd love to hear more about what I can improve on, and I trust that you wouldn't exploit my security weakness within the project, at least no so much that I start receiving bills from going over request limits of free plan.

It's ok if you don't have enough time, I'm asking for charity, afterall 😃 but I'd really appreciate it if you do!

**Comment by Karczel** [comment]
Is the issue resolved on your end or further changes are needed?
